### ISSUE TITLE
Wrong binary path when Ryujinx is installed using a package manager.

### ISSUE THREAD

**Issue by bernharl** [CapitaineJSparrow/emusak-ui#101]
**Is your feature request related to a problem? Please describe.**
emusak cheks if a given folder is a Ryujinx folder by looking for the binary. Thing is, I have Ryujinx installed via my package manager, meaning the binary is in /usr/bin, while the config, firmware and product key are stores in ~/.config/Ryujinx

**Describe the solution you'd like**
Support a global install.

**Describe alternatives you've considered**
I bypassed this by creating an empty file called Ryujinx in the folder.

**Comment by stromcon** [comment]
Thanks for reporting @bernharl I'll take a look ! Can u specify os and package manager used ?

**Comment by bernharl** [comment]
I'm on Arch Linux, so the package manager is Pacman. I used this AUR package: https://aur.archlinux.org/packages/yuzu-early-access/

**Comment by CapitaineJSparrow** [comment]
@bernharl I'm adressing this issue, can you confirm when you installed Ryujinx with your package manager it is installed globally (available in path) ? 

So if you type `ryujinx` in terminal it is found ? So I can detect ryujinx is installed globally by looking if ryujinx is in path

**Comment by bernharl** [comment]
It is available in PATH, yes :)

**Comment by FrogAddict** [comment]
> I'm on Arch Linux, so the package manager is Pacman. I used this AUR package: https://aur.archlinux.org/packages/yuzu-early-access/

You sure that that is the right AUR package? Looks like a Yuzu EA package to me, rather than a Ryujinx one.

**Comment by bernharl** [comment]
Right! Copied the wrong link. This is the package: https://aur.archlinux.org/packages/ryujinx-git

**Comment by acidflare** [comment]
> The program is case sensitive, and does not look for the file "ryujinx" instead it looks for "Ryujinx" on Linux. I hard linked into `.config/Ryujinx/` with the following command: _**(I do not know if there is any security implications in hard-linking a file under root on to the userspace)**_ `sudo ln -PL /usr/bin/ryujinx $HOME/.config/Ryujinx/Ryujinx`
> 
> Tell the program to look inside: `.config/Ryujinx/` _[EDIT]_ Noticed that if you use `pamac` to build Ryujinx it will install it in `/opt` compared to `paru`. Keep that in mind when hard-linking.
> 
> ![Screenshot_20211006_161916](https://user-images.githubusercontent.com/70252656/136287616-eb0e5e95-4792-49a2-8d6c-9b93b2dc6be7.png)

The program isn't case sensitive, Linux systems use case sensitivity globally, /usr/bin/ and /Usr/bin would be different directories the same as Program and program are different files.

Also pamac won't search the AUR without paru or yay installed. That's an intended feature, it's only a GUI that uses several backends, it's the same as KDE's Discover, it's a front-end that can use multiple back-ends to provide results from multiple sources.

@CaptitaineJSparrow paru installs ryujinx to /opt/ryujinx/ryujinx on arch with links to the executable placed in /usr/bin which itself is linked to /bin. I just ran into this issue myself when trying to configure emusak, My flatpak installation of yuzu right away though. I had to use double commander's search function to find out where ryujinx was installed to, tried /home/user/.config/ryujinx , /bin and /usr/bin but none of the folders were valid to emusak.
Maybe that should be hardcoded so AUR installations are detected instantly the same as flatpaks for yuzu are.

**Comment by CapitaineJSparrow** [comment]
Meanwhile i'd recommend to use for linux either pinejinx for ryujinx, or [Yuzu EA continuous integration from pineappleEA](https://github.com/pineappleEA/pineapple-src/releases/tag/continuous) where you have an appImage which self updates when there is new updates to yuzu EA

**Comment by acidflare** [comment]
for Yuzu there are 2 locations on linux for the config files, which location depends on how you run it. 
AppImage has it's files stored in /home/username/.local/share/yuzu/
Flatpak has it's files stored in /home/username/.var/app/org.yuzu_emu.yuzu/data/yuzu/

Using the package manager is just much more efficient with keeping the application updated when the system is updated, Pinejinx will keep ryujinx updated at the same frequency as the aur as it's script pulls from github then builds the application.

As for Yuzu the sandbox is for the application dependencies, for example I have the tytan build of obs installed which uses it's own version of ffmpeg. If I wanted to install Yuzu-git from the AUR I would need to replace that version of ffmpeg with the regular one found in the arch repo which would subsequently break my obs install, it would send me into a never-ending loop of juggling dependencies for different software. The flatpak and AppImage containers solve this issue by including the all of the software needed to run the application.

To put this all in easier to understand terms, flatpak is a sandbox where as appimage is a container. Both are containerized versions but with different methods, flatpak is essentially a linux os within a linux os and an AppImage is an executable program that contains the software along with all of the dependencies to run the application.

After taking another look at emusak it seems that it's not actually locating yuzu correctly, it's showing the windows appdata/roaming/yuzu location although my games are all listed there properly which is a tad confusing.

Most people that use arch linux will opt to use their package manager and an AUR helper like yay or paru instead of using another piece of software to install an emulator especially when the github repo of ryujinx and yuzu automatically pushes changes done in their repos to the AUR. Which results in users having the same update frequency as someone who clones the repo and builds it themselves

Hopefully this information can help you out with getting the linux version to be even better than it already is.

**Comment by CapitaineJSparrow** [comment]
ye as you said there is another task for flatpak, which is not done yet. For the AppImage and any other method, it will be handled automatically without the need to link yuzu (or ryujinx). In fact, it's already the case in emusak v1 (actual version) if you launched yuzu once and open emusak then.

**Comment by CapitaineJSparrow** [comment]
Hello everyone, I know it has been a while but I released emusak V2 as beta (current emusak will not auto update since it's a "pre-release"). This version is not asking for Ryujinx binary anymore unless you use "portable" mode (which is never the case if you use a package manager). https://github.com/CapitaineJSparrow/emusak-ui/releases 

Feedbacks appreciated

**Comment by CapitaineJSparrow** [comment]
Should have been fixed by emusak V2 https://github.com/CapitaineJSparrow/emusak-ui/releases
