### ISSUE TITLE
aur not being updated?

### ISSUE THREAD

**Issue by acidflare** [CapitaineJSparrow/emusak-ui#193]
Is the AUR not being updated with the beta version of 2.0?

**Comment by CapitaineJSparrow** [comment]
Hello @acidflare Since it's a beta the AUR and the auto updater included in windows version are updated at the moment (it's a "pre-release"). I know linux users are seeing  a banner which tell them there is a more recent available but for now ignore this until emusak V2 leave the beta or update manually it.

**Comment by acidflare** [comment]
I don't have a banner showing there is an update. However I am subscribed to notifications to the github repository as I am very interested in seeing where the future of this project leads.

**Comment by CapitaineJSparrow** [comment]
Probably cloud saves and at some point yuzu vulkan shares for shaders then ;)
