### ISSUE TITLE
v2: Feature request - Add the list view as an option 

### ISSUE THREAD

**Issue by RavenMacDaddy** [CapitaineJSparrow/emusak-ui#210]
**Is your feature request related to a problem? Please describe.**
Even if the grid view is very nice to look at, the list view present in v1 is a lot more efficient to use - having it available as an optional view option would be very appreciated.

**Comment by CapitaineJSparrow** [comment]
Hello @RavenMacDaddy I'll reject this feature but for multiple reasons : The goal with V2 has to reduce bandwidth usage because some people click on "download" button for everything even they are not playing the game. So add another click to download things should help emusak server to reduce his load, here are the usage for last 30 days:

![image](https://user-images.githubusercontent.com/6690149/154815590-0acd3aa1-2d60-4af3-bd5a-5bfe5dab9430.png)

I don't plan to add a grid view in short or mid term but I'll add a "favorites" feature where you can add some games (probably up to 10) and download shaders in one click from the main view. Also a "right click" will be implemented (right after the V2 release). 

Final word, thanks for all your contributions here it's very appreciated 👍

**Comment by RavenMacDaddy** [comment]
That's completely reasonable and something I didn't consider - thanks for the insight.
