### ISSUE TITLE
Steam proton game support

### ISSUE THREAD

**Issue by Pf4rR3R** [CapitaineJSparrow/emusak-ui#254]
Given the release of the Steamdeck and increasing support of Proton in games, it would be more than nice to have the functionality of emusak for steam games using proton as well. See e.g. https://www.reddit.com/r/linux_gaming/comments/t5xrho/dxvk_state_cache_for_fixing_stutter_in_apex/ that shares the shaders for apex legends.

**Comment by acidflare** [comment]
This is not needed as steam has this feature as an option on Linux. Shaders can be pre-cached and is shared between users, the option is turned off by default because of the additional bandwidth it uses. If you are playing a game after turning the option on and you compile a shader that wasn't pre-cached it will be sent to Valve's CDN servers so other players of that game who have the feature enabled can benefit from it.

The downside to this feature is that steam will validate all of your games every time you launch steam after restarting your system.

**Comment by CapitaineJSparrow** [comment]
Indeed Steam already do this feature, and EmuSAK is only focused on emulation for now

**Comment by acidflare** [comment]
If you did want to do something like this at some point, heroic and lutris would be the software you would want to target
