### ISSUE TITLE
ArchLinux, can't point hidden folders

### ISSUE THREAD

**Issue by RyukBerna** [CapitaineJSparrow/emusak-ui#260]
I can't point Yuz's binary folder on my Steam Deck.
I should point 
AppImage: ~/.local/share/yuzu
or
Flatpak: ~/.var/app/org.yuzu_emu.yuzu/data/yuzu/
but I can't see hidden folders inside Emusak UI.
I'm ana archnewbie so if I'm wrong sorry and tell me where I'm messing up
:D

**Comment by CapitaineJSparrow** [comment]
You have to show hidden folder in dolphin settings ( dolphin is the name of the explorer on steam deck )

**Comment by RyukBerna** [comment]
Thank you for your quick response,
I already set dolphin to show hidden folders, i can't see them inside the Emusak directory search

**Comment by acidflare** [comment]
Use right-click in the dialog window on any entry then choose "Show hidden files" to show the hidden folders and files. Regardless of the chosen settings in your default file manager the gtk based file manager dialog will always default to hiding hidden files.

If you need to do some research into your new arch based os(welcome btw ;) ) check out the arch linux wiki there is loads of information there, I've been using an arch based OS(Garuda Linux) for almost a year now and I frequently visit the wiki for information.

**Comment by RyukBerna** [comment]
Thank you for helping,
I tried to add the".desktop" file and EmuSAK shows nothing,
I tried also to add the ".yuzu" file but same result.
Where am I wrong?

**Comment by acidflare** [comment]
Ahh that's a classical problem that is very common for those switching from Windows to any *nix based system. There's no such thing as a file extension on Linux, well there is but it's not important like it is on windows. A .desktop file is only a bash script that links to an executable file which is generally stored in /usr/bin/

Open a terminal and type /usr/bin/dolphin and it will open the dolphin file manager that should give you a better understanding of how things work.
Most likely you have ryujinx installed as a flatpak which runs the application in a container which iirc is still a bit finicky to get working with emusak.

If you want to learn more about the detailed information behind  Linux and how things works I highly suggest checking out and subscribing to distrotube on YouTube.

**Comment by RyukBerna** [comment]
Ok, I'm just confused because the program ask me to find the "yuzu binary folder" but i can't select folders, only files

**Comment by CapitaineJSparrow** [comment]
I'd suggest to use pineapple src https://github.com/pineappleEA/pineapple-src/releases/tag/continuous download app image mark it as executable open yuzu once and then reopen emusak. The default configuration will pint to this yuzu. Flatpak are not yet supported in emusak since it's sandboxing apps and point files to another location

**Comment by acidflare** [comment]
That's because they are hidden in what is known as a dot folder for example /home/username/.config/ is a dot folder where all of your config files are stored. The . in front of the folder name makes it hidden the same goes for files.

Captaine is correct though pineapple-src should fix the issue for you. SteamOS is a bit of a hurdle right now for certain things like emusak because of the immutable filesystem, it's not a feature other arch based distributions are using.

**Comment by CapitaineJSparrow** [comment]
Also pineapple src has the advantage to auto update yuzu and come with early access version so you have latest features. You can make yuzu flatpak work in emusak with a symlink but that's more advanced usage. Finally appImage does not require z mutable system which is nice because steam deck wipe every data outside of your user folder at every update

**Comment by RyukBerna** [comment]
Ok guys thank you very much!
