### ISSUE TITLE
[Suggestion] Add Downloading of PPTC

### ISSUE THREAD

**Issue by RyzenDew** [CapitaineJSparrow/emusak-ui#82]
PPTC and shaders go hand in hand for Ryujinx and adding this feature would Add out of the box smooth gameplay

**Comment by stromcon** [comment]
@RyzenDew That's definitely planned

**Comment by RyzenDew** [comment]
closing due to Karen's in emu world

**Comment by CapitaineJSparrow** [comment]
As you maybe see in emuworld I have stability issues with this feature depending on CPU but I'll probably give another try by splitting PPTC sharing accross CPU generation

**Comment by RyzenDew** [comment]
If you need a tester let me know

**Comment by Shahil-Ayato** [comment]
Imho not going to happen due to how complex the system for this would need to be. 

- you’d need separate sections for different manufacturers (AMD and Intel)

- and not only just that but likely would also need separate sections for different CPU architectures to avoid cache issues. 

- Finally PPTC caches can easily get invalidated if it’s made on a different system, I’ve seen some extensive testing regarding this so because of this alone this issue request should be closed.  

Being realistic it’s not going to be easy to maintain a system like this but if you wish to anyways be my guest. This was just my two-cents on the matter.

**Comment by CapitaineJSparrow** [comment]
Hey everyone, I gave another shot and I think @Shahil-Ayato is right on all the points. I'll close this feature, I thought it was technically possible but it seems to be *wayyyy* more complex. We were able to transfer ptc caches from 3600 to 5600x for example but not the opposite (same for intel) and it's just causing crashes for people. Splitting ptc caches accross CPU generation is not viable because there will not be enough submissions and I designed this software to work for anyone and not to have to study how is working on a CPU and why I got a crash in Ryujinx after I used Emusak.
